name: CI

on:
  push:
    # tags:
    #   - '*'
    branches:
      - 'main'

jobs:
  API-FEED:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: (1) UDAGRAM-API-FEED -- Build and push
        id: docker_build1
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:udagram-api-feed"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:latest

  API-USER:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: (2) UDAGRAM-API-USER -- Build and push
        id: docker_build2
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:udagram-api-user"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-user:latest

  REVERSE-PROXY:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: (3) UDAGRAM-REVERSE-PROXY -- Build and push
        id: docker_build3
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:udagram-reverseproxy"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-reverseproxy:latest

  FRONTEND:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: (4) UDAGRAM-FRONTEND -- Build and push
        id: docker_build4
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:udagram-frontend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-frontend:latest