name: CI

on:
  push:
    # tags:
    #   - '*'
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: (1) UDAGRAM-API-FEED -- Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-feed
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-feed:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: (2) UDAGRAM-API-USER -- Build and push
      #   id: docker_build2
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-user:${{ steps.vars.outputs.tag }}, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-api-user:latest

      # - name: (3) UDAGRAM-REVERSE-PROXY -- Build and push
      #   id: docker_build3
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-reverseproxy:${{ steps.vars.outputs.tag }}, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-reverseproxy:latest

      # - name: (4) UDAGRAM-FRONTEND -- Build and push
      #   id: docker_build4
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/udagram-frontend:${{ steps.vars.outputs.tag }}, ${{ secrets.DOCKERHUB_USERNAME }}/udagram-frontend:latest
